### ISSUE TITLE
node-gyp error

### ISSUE THREAD

**Issue by suenot** [suenot/kupi-terminal#16]
```yarn``` not works:
```
error /home/suenot/work/kupi-terminal/node_modules/scrypt: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/suenot/work/kupi-terminal/node_modules/scrypt
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.13.1 | linux | x64
gyp info find Python using Python version 3.7.4 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/home/suenot/work/kupi-terminal/node_modules/@lerna/add/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/suenot/work/kupi-terminal/node_modules/scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/suenot/work/kupi-terminal/node_modules/@lerna/add/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/suenot/.cache/node-gyp/12.13.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/suenot/.cache/node-gyp/12.13.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/suenot/work/kupi-terminal/node_modules/@lerna/add/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/suenot/.cache/node-gyp/12.13.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/suenot/work/kupi-terminal/node_modules/scrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: вход в каталог «/home/suenot/work/kupi-terminal/node_modules/scrypt/build»
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
  COPY Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  AR(target) Release/obj.target/scrypt_wrapper.a
  COPY Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt_smix.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/warnp.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/alg/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/insecure_memzero.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/scryptenc/scryptenc_cpuperf.o
  AR(target) Release/obj.target/scrypt_lib.a
  COPY Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
In file included from ../src/node-boilerplate/scrypt_common.cc:28:
../../nan/nan.h: В функции «void Nan::AsyncQueueWorker(Nan::AsyncWorker*)»:
../../nan/nan.h:2298:62: предупреждение: cast between incompatible function types from «void (*)(uv_work_t*)» {aka «void (*)(uv_work_s*)»} to «uv_after_work_cb» {aka «void (*)(uv_work_s*, int)»} [-Wcast-function-type]
 2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_common.cc:28:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h: В конкретизации «void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]»:
/home/suenot/.cache/node-gyp/12.13.1/include/node/node_object_wrap.h:84:78:   required from here
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:10004:16: предупреждение: cast between incompatible function types from «v8::WeakCallbackInfo<node::ObjectWrap>::Callback» {aka «void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)»} to «Callback» {aka «void (*)(const v8::WeakCallbackInfo<void>&)»} [-Wcast-function-type]
10004 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h: В конкретизации «void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]»:
../../nan/nan_object_wrap.h:65:61:   required from here
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:10004:16: предупреждение: cast between incompatible function types from «v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback» {aka «void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)»} to «Callback» {aka «void (*)(const v8::WeakCallbackInfo<void>&)»} [-Wcast-function-type]
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o
In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:
../../nan/nan.h: В функции «void Nan::AsyncQueueWorker(Nan::AsyncWorker*)»:
../../nan/nan.h:2298:62: предупреждение: cast between incompatible function types from «void (*)(uv_work_t*)» {aka «void (*)(uv_work_s*)»} to «uv_after_work_cb» {aka «void (*)(uv_work_s*, int)»} [-Wcast-function-type]
 2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h: В конструкторе «NodeScrypt::Params::Params(const v8::Local<v8::Object>&)»:
../src/node-boilerplate/inc/scrypt_common.h:39:48: предупреждение: «v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)» устарело: Use maybe version [-Wdeprecated-declarations]
   39 |       N(obj->Get(Nan::New("N").ToLocalChecked())->Uint32Value()),
      |                                                ^
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/v8-internal.h:14,
                 from /home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:25,
                 from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:3457:51: замечание: объявлено здесь
 3457 |   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
      |                                                   ^~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8config.h:311:3: замечание: в определении макроса «V8_DEPRECATED»
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:39:63: ошибка: no matching function for call to «v8::Value::Uint32Value()»
   39 |       N(obj->Get(Nan::New("N").ToLocalChecked())->Uint32Value()),
      |                                                               ^
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:2611:41: замечание: candidate: «v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const»
 2611 |   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
      |                                         ^~~~~~~~~~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:2611:41: замечание:   кандидат ожидает 1 аргумент, 0 предоставлено
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:40:48: предупреждение: «v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)» устарело: Use maybe version [-Wdeprecated-declarations]
   40 |       r(obj->Get(Nan::New("r").ToLocalChecked())->Uint32Value()),
      |                                                ^
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/v8-internal.h:14,
                 from /home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:25,
                 from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:3457:51: замечание: объявлено здесь
 3457 |   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
      |                                                   ^~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8config.h:311:3: замечание: в определении макроса «V8_DEPRECATED»
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:40:63: ошибка: no matching function for call to «v8::Value::Uint32Value()»
   40 |       r(obj->Get(Nan::New("r").ToLocalChecked())->Uint32Value()),
      |                                                               ^
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:2611:41: замечание: candidate: «v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const»
 2611 |   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
      |                                         ^~~~~~~~~~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:2611:41: замечание:   кандидат ожидает 1 аргумент, 0 предоставлено
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:41:48: предупреждение: «v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)» устарело: Use maybe version [-Wdeprecated-declarations]
   41 |       p(obj->Get(Nan::New("p").ToLocalChecked())->Uint32Value()) {}
      |                                                ^
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/v8-internal.h:14,
                 from /home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:25,
                 from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:3457:51: замечание: объявлено здесь
 3457 |   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
      |                                                   ^~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8config.h:311:3: замечание: в определении макроса «V8_DEPRECATED»
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:41:63: ошибка: no matching function for call to «v8::Value::Uint32Value()»
   41 |       p(obj->Get(Nan::New("p").ToLocalChecked())->Uint32Value()) {}
      |                                                               ^
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:2611:41: замечание: candidate: «v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const»
 2611 |   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
      |                                         ^~~~~~~~~~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:2611:41: замечание:   кандидат ожидает 1 аргумент, 0 предоставлено
In file included from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_async.h: В функции-члене «virtual void ScryptAsyncWorker::HandleErrorCallback()»:
../src/node-boilerplate/inc/scrypt_async.h:53:29: предупреждение: «v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const» устарело [-Wdeprecated-declarations]
   53 |       callback->Call(1, argv);
      |                             ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:
../../nan/nan.h:1740:3: замечание: объявлено здесь
 1740 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_params_async.h: В конструкторе «ScryptParamsAsyncWorker::ScryptParamsAsyncWorker(Nan::NAN_METHOD_ARGS_TYPE)»:
../src/node-boilerplate/inc/scrypt_params_async.h:35:36: ошибка: no matching function for call to «v8::Value::NumberValue()»
   35 |       maxtime(info[0]->NumberValue()),
      |                                    ^
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:2608:39: замечание: candidate: «v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const»
 2608 |   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
      |                                       ^~~~~~~~~~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:2608:39: замечание:   кандидат ожидает 1 аргумент, 0 предоставлено
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_params_async.h:36:39: ошибка: no matching function for call to «v8::Value::NumberValue()»
   36 |       maxmemfrac(info[1]->NumberValue()),
      |                                       ^
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:2608:39: замечание: candidate: «v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const»
 2608 |   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
      |                                       ^~~~~~~~~~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:2608:39: замечание:   кандидат ожидает 1 аргумент, 0 предоставлено
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_params_async.h:37:36: ошибка: no matching function for call to «v8::Value::IntegerValue()»
   37 |       maxmem(info[2]->IntegerValue()),
      |                                    ^
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:2609:40: замечание: candidate: «v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const»
 2609 |   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
      |                                        ^~~~~~~~~~~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:2609:40: замечание:   кандидат ожидает 1 аргумент, 0 предоставлено
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_params_async.h:38:39: ошибка: no matching function for call to «v8::Value::IntegerValue()»
   38 |       osfreemem(info[3]->IntegerValue())
      |                                       ^
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:2609:40: замечание: candidate: «v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const»
 2609 |   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
      |                                        ^~~~~~~~~~~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:2609:40: замечание:   кандидат ожидает 1 аргумент, 0 предоставлено
../src/node-boilerplate/scrypt_params_async.cc: В функции-члене «virtual void ScryptParamsAsyncWorker::HandleOKCallback()»:
../src/node-boilerplate/scrypt_params_async.cc:23:67: предупреждение: «bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)» устарело: Use maybe version [-Wdeprecated-declarations]
   23 |   obj->Set(Nan::New("N").ToLocalChecked(), Nan::New<Integer>(logN));
      |                                                                   ^
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/v8-internal.h:14,
                 from /home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:25,
                 from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:3403:22: замечание: объявлено здесь
 3403 |                 bool Set(Local<Value> key, Local<Value> value));
      |                      ^~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8config.h:311:3: замечание: в определении макроса «V8_DEPRECATED»
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/node-boilerplate/scrypt_params_async.cc:24:64: предупреждение: «bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)» устарело: Use maybe version [-Wdeprecated-declarations]
   24 |   obj->Set(Nan::New("r").ToLocalChecked(), Nan::New<Integer>(r));
      |                                                                ^
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/v8-internal.h:14,
                 from /home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:25,
                 from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:3403:22: замечание: объявлено здесь
 3403 |                 bool Set(Local<Value> key, Local<Value> value));
      |                      ^~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8config.h:311:3: замечание: в определении макроса «V8_DEPRECATED»
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/node-boilerplate/scrypt_params_async.cc:25:64: предупреждение: «bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)» устарело: Use maybe version [-Wdeprecated-declarations]
   25 |   obj->Set(Nan::New("p").ToLocalChecked(), Nan::New<Integer>(p));
      |                                                                ^
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/v8-internal.h:14,
                 from /home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:25,
                 from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:3403:22: замечание: объявлено здесь
 3403 |                 bool Set(Local<Value> key, Local<Value> value));
      |                      ^~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8config.h:311:3: замечание: в определении макроса «V8_DEPRECATED»
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/node-boilerplate/scrypt_params_async.cc:32:25: предупреждение: «v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const» устарело [-Wdeprecated-declarations]
   32 |   callback->Call(2, argv);
      |                         ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:
../../nan/nan.h:1740:3: замечание: объявлено здесь
 1740 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
In file included from /home/suenot/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h: В конкретизации «void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]»:
/home/suenot/.cache/node-gyp/12.13.1/include/node/node_object_wrap.h:84:78:   required from here
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:10004:16: предупреждение: cast between incompatible function types from «v8::WeakCallbackInfo<node::ObjectWrap>::Callback» {aka «void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)»} to «Callback» {aka «void (*)(const v8::WeakCallbackInfo<void>&)»} [-Wcast-function-type]
10004 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h: В конкретизации «void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]»:
../../nan/nan_object_wrap.h:65:61:   required from here
/home/suenot/.cache/node-gyp/12.13.1/include/node/v8.h:10004:16: предупреждение: cast between incompatible function types from «v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback» {aka «void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)»} to «Callback» {aka «void (*)(const v8::WeakCallbackInfo<void>&)»} [-Wcast-function-type]
make: *** [scrypt.target.mk:129: Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Ошибка 1
make: выход из каталога «/home/suenot/work/kupi-terminal/node_modules/scrypt/build»
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/suenot/work/kupi-terminal/node_modules/@lerna/add/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.3.12-1-MANJARO
gyp ERR! command "/home/suenot/.nvm/versions/node/v12.13.1/bin/node" "/home/suenot/work/kupi-terminal/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/suenot/work/kupi-terminal/node_modules/scrypt
```

**Comment by suenot** [comment]
Problem in my settings of Manjaro, it can't build C++ modules with node-gyp: scrypt, electron, node-sass. In future versions this modules will be removed.
